---
# tasks file for tomcat

- name: Stop tomcat before update
  service:
    name: "{{ tomcat_daemon_name }}"
    state: stopped
  when: tomcat_update

- import_tasks: install.yml
- import_tasks: configure.yml
