---

- include: "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  static: no
  tags:
    - setup

- name: Configure tomcat
  template:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
  with_items:
    - src: tomcat-users.xml.j2
      dest: "{{ tomcat_user[0].home }}/conf/tomcat-users.xml"
    - src: context.xml.j2
      dest: "{{ tomcat_user[0].home }}/webapps/host-manager/META-INF/context.xml"
    - src: context.xml.j2
      dest: "{{ tomcat_user[0].home }}/webapps/manager/META-INF/context.xml"
  notify:
    - restart tomcat
  tags:
    - setup
