---

- include: "setup-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  static: no

- name: Configure tomcat
  template:
    src: "{{ item.src}}"
    dest: "{{ item.dest }}"
  with_items:
    - src: conf/server.xml.j2
      dest: "{{ tomcat_install_dir }}/conf/server.xml"
    - src: conf/tomcat-users.xml.j2
      dest: "{{ tomcat_install_dir }}/conf/tomcat-users.xml"
    - src: conf/context.xml.j2
      dest: "{{ tomcat_install_dir }}/webapps/host-manager/META-INF/context.xml"
    - src: conf/context.xml.j2
      dest: "{{ tomcat_install_dir }}/webapps/manager/META-INF/context.xml"
    - src: bin/setenv.sh.j2
      dest: "{{ tomcat_install_dir }}/bin/setenv.sh"
  notify:
    - restart tomcat
